# Spring Data Source Configuration (PostgreSQL avec Fallback H2)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/tictactoedb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# Hibernate & JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
